/**
 * English copy for the homepage and the asset gallery page.
 * Keys are exact DOM text fragments: text split by <br> or inline elements is keyed per piece.
 * Names already translated in showcase-language.ts (characters, skills) are left to that dictionary.
 */
export const HOME_ENGLISH: Record<string, string> = {
  '鹈鹕 429 · 从一场降智风暴开始': 'Pelican 429 · It began with a brain-drain storm',
  '资源展示 · 鹈鹕 429': 'Asset gallery · Pelican 429',
  '鹈鹕 429': 'Pelican 429', '鹈鹕 429 首页': 'Pelican 429 home',

  // Header and hero
  '一场越过边界的冒险': 'An adventure beyond the boundary',
  '网站导航': 'Site navigation', '游戏介绍': 'About', '章节': 'Chapters', '角色': 'Characters',
  '开源': 'Open source', '赞助': 'Sponsor', '资源展示': 'Asset gallery', '进入游戏': 'Play now', '继续游戏': 'Continue game',
  'GitHub 仓库': 'GitHub repository',
  '鹈鹕站在黑洞前哨的石台上，远处是蓝天下的未来都市与海面': 'The pelican stands on a stone ledge at the black hole outpost, a future city and the sea under blue skies in the distance',
  '独立横版动作冒险 · 主线制作中': 'Indie side-scrolling action adventure · Main story in development',
  '世界拒绝访问。': 'The world denied access.',
  '我们继续向前。': 'We keep moving forward.',
  '从一场 AGI 风暴，走进算力与废墟交织的世界。': 'From an AGI storm into a world where compute and ruins intertwine.',
  '变换形态，穿过边界，找回属于每个人的未来。': 'Change form, cross the boundary, and win back a future that belongs to everyone.',
  '观看序章': 'Watch the prelude', '源码': 'Source',
  '浏览器即开即玩 · 无需下载 · 推荐电脑键盘与鼠标': 'Play instantly in your browser · No download · Keyboard and mouse recommended',
  '向下探索': 'Scroll to explore',

  // 01 World
  '一只鹈鹕，': 'One pelican,',
  '一个不愿放弃的世界。': 'one world that refuses to give up.',
  '当通往未来的道路被一道「429」切断，冒险才刚刚开始。': 'When a single “429” cuts off the road to the future, the adventure has only just begun.',
  '《鹈鹕 429》是一款正在制作中的横版动作冒险游戏。跟随 Grassy 与鹈鹕，在自然遗迹和巨大机房之间探索，寻找穿越封锁的下一条路。': 'Pelican 429 is a side-scrolling action adventure in development. Follow Grassy and the pelican through natural ruins and colossal server halls in search of the next way past the blockade.',
  '越过边界': 'Cross the boundary',
  '走动、跳跃与飞行，从检修通道深入庞大的算力设施。': 'Walk, jump, and fly from the service corridors deep into a vast compute facility.',
  '换个形态前进': 'Change form to advance',
  '切换鹈鹕与人形 Grassy，体验不同的移动与动作表现。': 'Switch between the pelican and human Grassy, each with its own movement and moves.',
  '为前路而战': 'Fight for the road ahead',
  '瞄准、攻击、释放技能，在演示场景中熟悉战斗节奏。': 'Aim, attack, and unleash skills to learn the rhythm of combat in the demo scene.',

  // 02 Journey
  '先听故事，再走进世界。': 'Hear the story, then step into the world.',
  '从序章出发，或直接体验正在生长的主线。': 'Start with the prelude, or jump straight into the main story as it grows.',
  'Grassy 在雨雪夜的房间中编程': 'Grassy coding in a room on a night of rain and snow',
  '序章 · 可观看': 'Prelude · Watch now',
  'AGI 降智风暴': 'AGI Brain-Drain Storm',
  '四个音符把 AGI 推向 99%，一道 429 劈下。黑暗里，新的旋律重新响起。': 'Four notes push AGI to 99%, and a 429 strikes. In the dark, a new melody rises again.',
  '观看序章动画': 'Watch the prelude animation',
  '山体算力堡垒全景：三层机房、屋顶冷却阵列与黑洞前哨': 'Panorama of the mountain compute fortress: three server floors, the rooftop cooling array, and the black hole outpost',
  '主线 · 开发中试玩': 'Main story · Early playable',
  '深入山体堡垒': 'Into the mountain fortress',
  '从黑洞前哨出发，穿过堡垒门禁，深入多层机房：清理外围守卫、击退 Tibo、击败 Sam，让前沿模型重新开放。主线仍在制作中，剧情与关卡将持续完善。': 'Set out from the black hole outpost, slip past the fortress gates, and descend through the server floors: clear the outer guards, drive back Tibo, and defeat Sam to reopen frontier models. The main story is still in development, and its story and levels will keep improving.',
  '进入主线试玩': 'Play the main story',
  '游玩提示': 'Play tips',
  '出发前的小提示': 'Before you set out',
  '推荐使用电脑游玩；具体操作以游戏内提示为准。': 'Best played on a computer; follow the in-game prompts for controls.',
  '切换形态': 'Switch form', '鼠标': 'Mouse', '瞄准与攻击': 'Aim and attack',

  // 03 Cast
  '认识这趟旅程里的每一位。': 'Meet everyone on this journey.',
  '同伴、首领与堡垒守卫，全部来自游戏里的真实模型。': 'Companions, bosses, and fortress guards, all shown with their real in-game models.',
  '主角': 'Heroes', '首领': 'Bosses', '堡垒守卫': 'Fortress guards',
  '戴绿帽、系红围巾的白色鹈鹕': 'A white pelican in a green cap and red scarf',
  '吐水普攻、鱼群轰炸、振翅突进、吞弹反击': 'Water spit, fish barrage, wing dash, and swallow counter',
  '穿红色上衣、背着键盘装备的少年 Grassy': 'Grassy, a boy in a red top carrying his keyboard gear',
  '在黑暗中发出青色微光的光子': 'Photon, glowing a soft cyan in the dark',
  '像萤火虫一样的一团活的光，一路引导': 'A living ball of light like a firefly, guiding the way',
  '穿黑色帽衫、戴重置胸章的 Tibo': 'Tibo in a black hoodie wearing a reset badge',
  '重置大师 · The Reset Master': 'The Reset Master',
  '机房核心的第一位首领，击退他才能解锁变身。': 'The first boss at the heart of the server halls. Drive him back to unlock transformation.',
  'Tibo 的技能': 'Tibo’s skills',
  '穿灰色毛衣、戴路由胸章的 Sam': 'Sam in a gray sweater wearing a routing badge',
  '模型路由者 · The Model Router': 'The Model Router',
  'Tibo 之后抵达的对手，击败他，前沿模型才能重新开放。': 'The rival who arrives after Tibo. Defeat him to reopen frontier models.',
  'Sam 的技能': 'Sam’s skills',
  '大头双钳的白色机器人欧米 OMI-01': 'OMI-01, a big-headed white robot with twin clamps',
  '欧米 OMI-01': 'OMI-01',
  '四足机械犬巡线犬': 'Line Hound, a four-legged robot dog',
  '四旋翼无人机哨蜂': 'Watch Wasp, a quadcopter drone',
  '带黄色机械臂的轮式搬运机器人搬山': 'Loadmaster, a wheeled hauler robot with a yellow arm',
  '在角色展示场查看实时 3D 模型': 'See the live 3D models in the character showcase',

  // 04 Source
  '源码公开，': 'Source available,',
  '欢迎一起建造。': 'come build with us.',
  '游戏逻辑、关卡生成与角色资源全部公开在 GitHub。提交 Issue、参与讨论，或直接 fork 一份，造出你自己的鹈鹕冒险。': 'Game logic, level generation, and character assets are all public on GitHub. Open an issue, join the discussion, or fork it and build your own pelican adventure.',
  '技术栈': 'Tech stack', '种子化世界生成': 'Seeded world generation',
  '许可协议：': 'License: ',
  '个人、团队、公司都可以免费使用、学习、修改和再分发': 'Individuals, teams, and companies may use, study, modify, and redistribute it for free',
  '魔改、二次创作、做成你自己的作品免费发布，都没问题': 'Remix it, build derivative works, or release your own creation for free, all welcome',
  '唯一的限制：不要把本项目或主要依赖它功能的东西拿去收费售卖': 'The only restriction: do not sell this project, or anything whose value mainly comes from its features',
  '分发时保留许可声明即可；有商业合作想法，欢迎联系作者另行授权。': 'Just keep the license notice when you distribute it. For commercial collaboration, contact the author for a separate license.',
  '阅读完整许可': 'Read the full license',
  '在 GitHub 查看': 'View on GitHub', '反馈问题': 'Report an issue',
  '本地运行命令': 'Run locally',
  '# 克隆仓库': '# Clone the repository',
  '# 安装依赖并启动': '# Install dependencies and start',

  // 05 Sponsor & contact
  '赞助与联系': 'Sponsor & contact',
  '感谢赞助方的支持；有问题、想法或建议，欢迎来聊。': 'Thanks to our sponsor for the support. Questions, ideas, or suggestions? Come say hi.',
  '本项目由 PomoAI 中转站赞助': 'This project is sponsored by PomoAI',
  'PomoAI · 大模型 API 中转服务': 'PomoAI · LLM API relay service',
  '访问 www.pomoai.ai': 'Visit www.pomoai.ai',
  '联系作者': 'Contact the author',
  '反馈问题、提出建议或交流想法，欢迎在 GitHub Issues 留言、在 X 上关注 @grassy429，或扫码加入微信交流群。': 'To report a problem, suggest an idea, or just chat, leave a message on GitHub Issues, follow @grassy429 on X, or scan the code to join the WeChat group.',
  '鹈鹕 429 微信交流群二维码': 'Pelican 429 WeChat group QR code',
  '作者头像': 'Author avatar', '小草': 'Grassy',
  '作者 · @grassy429': 'Author · @grassy429', '关注 X': 'Follow on X', '微信扫码': 'Scan with WeChat', '加入交流群': 'to join the group',
  '在 X 上关注 @grassy429': 'Follow @grassy429 on X', '微信交流群': 'WeChat group', '微信扫码加入交流群': 'Scan with WeChat to join the group',
  '微信扫码加入交流群 · 二维码定期更新，失效请通过 Issues 联系': 'Scan with WeChat to join the group · The QR code is refreshed regularly; if it has expired, reach us via Issues',

  // 06 Credits
  '特别感谢': 'Special thanks',
  '这只鹈鹕能飞起来，离不开这些伙伴。': 'This pelican could not have taken flight without these partners.',
  'AI 协作': 'AI collaboration',
  '感谢三个模型，全程封号 + 降智': 'Thanks to three models — banned and dumbed down the whole way',
  '代码、关卡、剧情与无数次调试，都有它们在一起熬夜。': 'Code, levels, story, and countless debugging sessions: they stayed up late with us through all of it.',
  '协作模型': 'Collaborating models',
  '3D 模型制作': '3D modeling',
  '感谢付费 3D 模型制作服务': 'Thanks to a paid 3D modeling service',
  '角色与怪物的基础模型由 Hyper3D Rodin 付费生成，让每一位登场角色都有了真实的身体。': 'The base models for characters and monsters were generated with the paid Hyper3D Rodin service, giving every character a real body.',
  '3D 模型服务': '3D modeling service',
  '开源项目': 'Open-source projects',
  '感谢各种开源项目': 'Thanks to the open-source community',
  '站在开源社区的肩膀上：渲染、构建、类型系统与模型绑定动画，全部来自开源工具。': 'Standing on the shoulders of the open-source community: rendering, builds, the type system, and model rigging and animation all come from open-source tools.',

  // Footer
  '前沿模型，人人有权使用。': 'Frontier AI is everyone’s right.',
  '页脚导航': 'Footer navigation', '赞助 PomoAI': 'Sponsor: PomoAI',
  '主线制作中，下一段旅程正在发生。': 'The main story is in development; the next journey is already underway.',

  // Asset gallery page
  '返回首页': 'Back to home', '资源展示导航': 'Asset gallery navigation',
  '当前游戏的全部开发场景。查看角色与动作、场景资源、声音，或进入各个关卡自由探索。': 'Every development scene in the current game. Inspect characters and actions, scene assets, and sounds, or explore each level freely.',
  '全部开发场景': 'All development scenes', '声音目录': 'Sound library',
};
