/** Copy shared by the character, resource and scene showcase views. */
export const SHOWCASE_ENGLISH: Record<string, string> = {
  '展示方式': 'View', '横版实战': 'Side-scrolling arena', '模型查看': 'Model inspection', '移动施法': 'Attack movement', '静止': 'Standing',
  '钳卫': 'Gatekeeper', '巡线犬': 'Line Hound', '哨蜂': 'Watch Wasp', '搬山': 'Loadmaster',
  '堡垒运维队': 'Fortress maintenance team', '堡垒运维队 · 四怪': 'Fortress · Four enemies', '堡垒运维队 · 八技能': 'Fortress · Eight skills',
  '夹臂横扫': 'Clamp sweep', '突进夹击': 'Dash clamp', '直线扑冲': 'Pounce', '落地震击': 'Landing shock',
  '悬停投弹': 'Bomb drop', '铝热剂投放': 'Thermite drop', '前方下砸': 'Overhead smash', '低位横扫': 'Low sweep',
  '外观对比': 'Appearance comparison', '随机机群': 'Drone variants',
  '出生时固定机身配色、桨叶配色和双叶或三叶形态': 'Fixed body and propeller colors with two or three blades, chosen at spawn.',
  '无人机 · 投弹与随机外观': 'Drones · Payloads and variants',
  '白色机身与随机饰色、倾斜飞行、投弹爆炸及铝热剂持续燃烧。': 'White shells with varied accents, banking flight, bomb explosions, and persistent thermite fire.',
  '移动': 'Move', '正侧面参考': 'Front and side references', '绘制的建模参考 · 正面与侧面': 'Modeling reference · Front and side',
  '检查真实模型的轮廓、材质与接地': 'Inspect the game model, materials, and ground contact',
  '实际追踪移动与机械步态': 'Real tracking movement and mechanical gait',
  '技能一：真实准备、攻击判定与收招': 'Skill 1: real startup, damage, and recovery',
  '技能二：真实准备、攻击判定与收招': 'Skill 2: real startup, damage, and recovery',
  '鹈鹕吐水命中、闪光与击退': 'Pelican water impact, flash, and knockback',
  '钳卫、巡线犬、FPV 哨蜂和搬山；共享第一章模型与双技能，支持正面和侧面检查。': 'Gatekeeper, Line Hound, FPV Watch Wasp, and Loadmaster. Shared chapter models and two skills each; inspect front and side views.',
  '四种敌人的两个技能，展示真实伤害与动作时间轴。': 'Two skills per enemy, with actual damage and animation timing.',

  '双向变身': 'Transformation', '鹈鹕 → 主角': 'Pelican → Grassy', '主角 → 鹈鹕': 'Grassy → Pelican',
  '鹈鹕 ↔ 主角 · 双向变身': 'Pelican ↔ Grassy · Transformation',
  '羽毛生长或收退，身体随之换形；按 F 可在鹈鹕和 Grassy 之间切换。': 'Feathers grow or retract as the body changes form. Press F to switch between Pelican and Grassy.',
  '羽毛收退、翅膀恢复为双臂，身体抬高变为 Grassy；手动模式按 F 可再次变身': 'Feathers retract, wings become arms, and the body rises into Grassy. Press F in manual mode to transform again.',
  '羽毛从肩背沿手臂生长，身体收短变为鹈鹕；手动模式按 F 可再次变身': 'Feathers grow from the shoulders along the arms as the body shortens into a pelican. Press F in manual mode to transform again.',
  '羽毛生长': 'Feathers growing', '羽毛收退': 'Feathers retracting', '身体换形': 'Body changing', '变身中': 'Transforming', '人类形态': 'Human form', '鹈鹕形态': 'Pelican form',
  'F 变为鹈鹕': 'F → Pelican', 'F 变为主角': 'F → Grassy',
  '点击画面后：A/D 移动 · Space 跳跃 · Shift 慢走 · J/K 普攻 · 右键副攻 · 1–3 技能 · E 大招 · R 骑车 · F 变身': 'Click the view: A/D move · Space jump · Shift walk · J/K attack · RMB secondary · 1–3 skills · E ultimate · R ride · F transform',
  '地形视角': 'Terrain view', '斜侧': 'Oblique',
  '无风': 'Calm', '微风': 'Breeze', '中风': 'Moderate wind', '大风': 'Strong wind', '暴风': 'Gale', '自动': 'Auto',
  '关闭预览': 'Close preview', '进入游戏 ↗': 'Enter game ↗', '资源变体选择': 'Choose asset variant', '动作选择': 'Choose action',
  '模型精细度': 'Model detail', '准备场景': 'Preparing scene', '点击画面后：A/D 移动 · Space 跳跃 · Shift 慢走 · J/K 攻击 · R 骑车': 'Click the view: A/D move · Space jump · Shift walk · J/K attack · R ride',
  '环境': 'Environment', '地上': 'Above ground', '地下': 'Underground', '暂停': 'Pause', '重播': 'Replay', '循环': 'Loop',
  '朝右 →': 'Face right →', '← 朝左': '← Face left', '速度': 'Speed', '＋ 添加对照': '＋ Add comparison', '手动控制': 'Manual control',
  '缩放': 'Zoom', '镜头缩放': 'Camera zoom', '动作进度': 'Action progress', '完整洞穴': 'Complete cave',
  '添加同项目对照': 'Compare this item', '暂停此预览': 'Pause this preview', '播放此预览': 'Play this preview',
  '角色动作与精细度': 'Character actions and detail', '历史模型版本选择': 'Choose historical model',
  '纯资源模式': 'Asset only', '场景模式': 'Scene mode', '瓦片网格': 'Tile grid', '站立位置': 'Standing surfaces',
  '鹈鹕比例参照': 'Pelican scale reference', '检视补光': 'Inspection light', '已暂停调度': 'Preview paused',
  '● 实时预览': '● Live preview', 'Ⅱ 已暂停': 'Ⅱ Paused', 'Ⅱ 暂停': 'Ⅱ Pause', '▶ 播放': '▶ Play',
  '角色资料库导航': 'Character library navigation', '角色资料': 'Characters', '历史资料': 'History',
  '搜索目录': 'Search catalog', '资源分类目录': 'Asset categories', '角色多选目录': 'Select characters',
  '清空选择': 'Clear selection', '↗ 返回游戏': '↗ Return to game', '首页索引': 'Home',
  '完整资源目录（单独查看或分批预览）': 'Full asset catalog (individual or batch preview)',
  '▶ 全部播放': '▶ Play all', 'Ⅱ 全部暂停': 'Ⅱ Pause all', '↺ 全部重置': '↺ Reset all',
  '统一速度': 'Shared speed', '统一环境': 'Shared environment', '各自设置': 'Individual settings',
  '全部地上': 'All above ground', '全部地下': 'All underground', '同步对比': 'Sync comparison',
  '统一比例': 'Shared scale', '从同一起点播放；任一对比画面离屏时整组暂停': 'Play from the same point; pause the group when any view is offscreen',
  '按相同的世界尺寸取景，比较实际尺寸': 'Frame at the same world scale to compare real sizes',
  '独立预览 · 每个画面单独控制': 'Independent previews · Control each view separately',
  '游戏模型 · 原始材质 · 真实风动': 'Game models · Original materials · Real wind animation',
  '真实角色 · 真实物理 · 真实光照': 'Real characters · Real physics · Real lighting',
  '未选择': 'None selected', '完整游戏资源目录': 'Full game asset catalog', '完整目录': 'Full catalog',
  '上一批': 'Previous batch', '下一批': 'Next batch', '预览本批（替换当前卡片）': 'Preview this batch (replace current cards)',
  '切换分类直接预览一批，替换当前卡片；每批最多 8 张。点名称可单独查看。': 'Choose a category to preview one batch, replacing current cards. Up to 8 per batch. Click a name to view it alone.',
  '功能演示目录': 'Scene demo catalog',
  '瓦片组合': 'Tile layout', '悬空单格': 'Floating tile', '地面单格': 'Ground tile', '连续平地': 'Flat ground',
  '四种形状并列': 'Four shapes', '阶梯拼接': 'Joined steps', '多材质邻接': 'Mixed materials', '多材质固定对照': 'Fixed material comparison',
  '地形构图': 'Terrain composition', '单块与拼接设置': 'Single tile and joins', '顶层形状': 'Top shape',
  '整格（1 × 1）': 'Full tile (1 × 1)', '右升斜坡': 'Rising right slope', '左升斜坡': 'Rising left slope', '半格（1 × 0.5）': 'Half tile (1 × 0.5)',
  '植被层次': 'Vegetation layers', '完整植被': 'Full vegetation', '仅瓦片': 'Tiles only', '瓦片 + 地被': 'Tiles + ground cover',
  '瓦片 + 地被 + 花草': 'Tiles + cover + flowers', '加入地被': 'Add ground cover', '加入花草': 'Add flowers', '再加花草': 'Add flowers',
  '生长环境': 'Growth habitat', '空旷地面': 'Open ground', '空旷': 'Open', '树下': 'Under trees', '近水岸边': 'Shore', '岸边': 'Shore', '沙漠': 'Desert',
  '种子': 'Seed', '资源种子': 'Asset seed', '下一种子': 'Next seed', '风力': 'Wind', '资源风力': 'Asset wind',
  '显示每格 1 × 1 世界单位的边界': 'Show the boundary of each 1 × 1 world tile',
  '显示游戏地形与树木平台的可站立顶面': 'Show walkable surfaces on terrain and tree platforms',
  '为地下资源提供固定柔光；关闭可查看场景原始光照': 'Add soft light to underground assets; turn off to inspect original lighting',
  '形状改变真实瓦片；邻格决定接缝。植被由暴露顶面、材质、坐标与环境生成。': 'Shape changes the real tiles; neighbors determine seams. Vegetation grows from exposed surfaces, materials, coordinates, and habitat.',
  '树枝平台是碰撞瓦片，外观由同一棵游戏树模型绘制。': 'Branch platforms use collision tiles, while the game tree model provides their appearance.',
  '屋顶瓦片负责碰撞，外观由游戏渔屋模型绘制。': 'Roof tiles provide collision, while the game fishing hut model provides their appearance.',
  '类型决定几何，种子控制实例参数；风力驱动游戏原有动画。自然花草按坐标与环境分布，不随此种子任意重排。': 'Type determines geometry; the seed controls instance details and wind drives the original game animation. Natural flowers follow coordinates and habitat, so this seed does not rearrange them.',
  '整组展示设置': 'Group preview settings', '更多整组设置': 'More group settings', '暂停动画': 'Pause animation', '播放动画': 'Play animation',
  '恢复本组默认': 'Restore group defaults', '展开详细设置': 'Show detailed settings', '收起详细设置': 'Hide detailed settings',
  '整组环境': 'Group environment', '各格环境': 'Each card', '整组风力': 'Group wind', '分格对照': 'Compare cards',
  '单格形状': 'Tile shape', '全部形状': 'All shapes', '整组植被': 'Group vegetation', '分层对照': 'Compare layers',
  '整组种子': 'Group seed', '应用种子': 'Apply seed', '换一组变化': 'Next set of variants', '整组速度': 'Group speed',
  '各格速度': 'Each card', '整组缩放': 'Group zoom', '各格缩放': 'Each card', '循环播放': 'Loop playback',
  '所有画面可见时统一播放，离屏时整组暂停': 'Play together while all views are visible; pause the group when one leaves the screen',
  '选择树种': 'Choose tree', '选择材质': 'Choose material', '起始种子': 'Starting seed', '统一种子': 'Shared seed',
  '八种构图使用同样大小的范围与游戏生成代码。点击换角度、拖动旋转；打开网格或站立位置检查结构，进入游戏可实际走动。': 'Eight compositions use the same size and game generation code. Click to change angle, drag to rotate, or inspect the grid and standing surfaces. Enter the game to walk through them.',
  '整格 1 × 1，半格 1 × 0.5；每卡从左到右八个游戏自然样本。点击换角度、拖动旋转；“换一组变化”查看下一批。': 'Full tiles are 1 × 1 and half tiles 1 × 0.5. Each card shows eight natural game samples. Click to change angle, drag to rotate, or select the next set.',
  '青线：真实可站立位置。点击画面换角度，拖动旋转；展开详细设置可单独检查每格。': 'Cyan lines mark real standing surfaces. Click to change angle, drag to rotate, or open detailed settings to inspect each card.',
  '多材质格保留游戏固定材质组合；其余格跟随顶部材质。': 'Mixed material tiles keep the game’s fixed combination; other tiles follow the selected material.',
  '植物按真实材质与生长规则出现；不适合生长的地面不会强行补花草。': 'Plants follow the real materials and growth rules; unsuitable ground stays bare.',
  '各格自动展开对照，标签显示当前实际设置；点击画面换角度，拖动旋转。': 'Cards expand automatically for comparison and show their current settings. Click to change angle or drag to rotate.',
  '角色图片资源': 'Character images', '原始图片待补充 · 下方可查看实时模型': 'Original images are pending · Inspect the live model below',
  '资源来源': 'Asset source', '归档模型与工程索引': 'Archived models and project index', '收起图片': 'Hide images', '展开图片': 'Show images',
  '图片分类': 'Image categories', '关闭': 'Close', '图片加载失败，请通过下方链接检查原文件。': 'Image failed to load. Check the original file using the link below.',
  '← 上一张': '← Previous', '下一张 →': 'Next →', '打开原文件 ↗': 'Open original ↗',
  '↓ 历史 3D 模型 · 选择版本并旋转查看': '↓ Historical 3D models · Choose a version and rotate',
  '↓ 正式 3D 角色 · 动作与精细度独立切换': '↓ Final 3D character · Choose action and detail independently',
  '↓ 实时 3D 模型 · 在下方直接切换动作': '↓ Live 3D model · Change actions below',
  '已确认的装备设定 · 推进飞行、键盘攻击与日常背负': 'Final equipment concepts · Powered flight, keyboard attacks, and everyday carry',
  '绘制的技能效果设定 · 概念图，非游戏实际渲染': 'Illustrated combat concepts · Not actual game renders',
  '飞行中施放四种键盘攻击的设定 · 概念图，非游戏实际渲染': 'Four keyboard attacks during flight · Concept art, not actual game renders',
  '归档模型的原始渲染图 · 下方可旋转查看真实模型': 'Original renders of archived models · Rotate the live model below',
  '已归档的角色造型探索': 'Archived character design explorations',
  '角色高度与场景、门框和鹈鹕的早期对照': 'Early character scale comparisons with scenes, doorways, and the pelican',
  '不同头身比例的设计探索': 'Character proportion studies', '最初的四方向设计稿': 'Initial four direction designs',
  '3.1 头身比例的四方向试稿': 'Four direction study at 3.1 head to body ratio',
  '母版确认前的四方向修订': 'Four direction revision before the master design',
  '正式母版的历史试稿': 'Earlier studies of the final master design',
  '主角造型与表情设定 · 点击查看完整角色卡': 'Main character design and expressions · Click to view the full card',
  '绘制的建模参考 · 正面、背面、左侧、右侧': 'Modeling references · Front, back, left, and right',
  '角色设计原图 · 点击缩略图查看大图': 'Original character art · Click thumbnails to enlarge',
  '立体风格设计图 · 静态图片': '3D style concept · Static image',
  '真实模型渲染截图 · 点击查看完整画面': 'Live model renders · Click to see the full image',
  '从平面到立体的过程截图与原画对照': 'From flat art to 3D · Process and concept comparisons',
  '历史模型截图 · 第一版至第四版': 'Historical model screenshots · Versions one through four',
  '骑行原画、动画素材与模型截图': 'Riding concept art, animation assets, and model screenshots',
  '装备概念': 'Equipment concepts', '战斗效果概念': 'Combat effect concepts', '空中技能概念': 'Airborne skill concepts', '历史模型多视图': 'Historical model views', '早期角色卡': 'Early character cards',
  '键盘单手连击': 'One-handed keyboard combo', 'Codex 实体光弹': 'Codex energy projectiles', 'Bug 虫群': 'Bug swarm', '概念图': 'Concept art',
  '空中键盘单手连击': 'Airborne one-handed keyboard combo', '空中 Codex 光弹': 'Airborne Codex projectiles', '空中 Bug 虫群': 'Airborne Bug swarm', '空中服务器超载': 'Airborne server overload',
  '场景比例对照': 'Scene scale comparison', '头身比例稿': 'Proportion studies', '早期四方向': 'Early four directions',
  '3.1 比例试稿': '3.1 proportion study', '四方向修订稿': 'Four direction revision', '母版试稿': 'Master design study',
  '角色卡': 'Character cards', '四方向参考': 'Four direction references', '2D 原画': '2D concept art',
  '3D 参考': '3D reference', '模型多视图': 'Model views', '演变对照': 'Design evolution',
  '历史版本': 'Historical versions', '骑行素材': 'Riding assets',
  '三分之四': 'Three quarter', '正面': 'Front', '背面': 'Back', '左侧': 'Left', '右侧': 'Right',
  '鹈鹕': 'Pelican', '原画、参考图与实时模型': 'Concept art, references, and live models',
  'Grassy · 人类': 'Grassy · Human', '正式装备角色 · 骑行、键盘战斗与推进飞行': 'Final equipment character · Riding, keyboard combat, and powered flight',
  '光子': 'Photon', '飞行微光 · 自由游弋与环境照明': 'Flying light · Free movement and ambient illumination',
  '训练假人': 'Training dummy', '受击、射击与漂浮': 'Hit, shoot, and float',
  '鱼类': 'Fish', '七种鱼的外形、游动与扑腾': 'Seven fish species, swimming and flopping',
  '自行车': 'Bicycle', '键盘战斗': 'Keyboard combat', '推进飞行': 'Powered flight', '基础动作': 'Basic actions',
  '静态模型': 'Static models', '宠物动作': 'Companion actions', '角色动作': 'Character actions',
  '待机': 'Idle', '观察呼吸、重心与配饰的轻微摆动': 'Watch subtle breathing, balance, and accessory movement',
  '走路': 'Walk', '慢速步态与脚底贴地': 'Slow gait and grounded feet',
  '跑步': 'Run', '加速跑动与身体跟随': 'Accelerated running and body follow through',
  '转身': 'Turn', '观察左右转向的过渡': 'Watch transitions between left and right turns',
  '跳跃 / 落地': 'Jump / land', '起跳、下落与落地的完整过程': 'Full jump, fall, and landing sequence',
  '飞行': 'Fly', '起跳后振翅上升': 'Take off and flap upward',
  '滑翔': 'Glide', '从高处展开翅膀滑翔': 'Spread wings and glide from a height',
  '游泳': 'Swim', '自动进入水池，观察浮力与划水': 'Enter the pool to inspect buoyancy and paddling',
  '战斗动作': 'Combat actions', '啄击': 'Peck', '对训练假人发动近战攻击': 'Melee attack against the training dummy',
  '喷水': 'Water shot', '嘴囊动作与水弹轨迹': 'Pouch movement and water projectile path',
  '吐鱼': 'Spit fish', '吐鱼时间轴与弹体颜色衔接': 'Fish projectile timing and color transition',
  '光球蓄力': 'Charge orb', '蓄力、吐射与动态照明': 'Charge, fire, and dynamic lighting',
  '吞弹反吐': 'Swallow and reflect', '等待来袭弹、吞入并反射': 'Wait for an incoming shot, swallow, and reflect it',
  '骑行动作': 'Riding actions', '上车': 'Mount', '从站立到骑乘的完整过渡': 'Complete transition from standing to riding',
  '骑行': 'Ride', '踩踏、车轮与身体的联动': 'Pedaling, wheels, and body move together',
  '下车': 'Dismount', '先上车，再演示主动下车': 'Mount first, then demonstrate an active dismount',
  '行为演示': 'Behavior demos', '站立': 'Stand', '检查轮廓、材质与接地': 'Inspect silhouette, materials, and ground contact',
  '受击 / 击退': 'Hit / knockback', '真实命中、闪白与受力位移': 'Real hit, white flash, and displacement',
  '射击': 'Shoot', '朝鹈鹕发射敌方弹体': 'Fire an enemy projectile at the pelican',
  '倒下 / 归位': 'Fall / reset', '受击归零后恢复生命并归位': 'Restore health and position after a fatal hit',
  '水中漂浮': 'Float in water', '水中浮力与阻尼': 'Buoyancy and drag in water',
  '鱼类品种': 'Fish species', '游动': 'Swim', '小鱼在水中漫游': 'A small fish roams in the water',
  '受惊逃离': 'Flee', '鹈鹕接近后加速逃离': 'Speed away when the pelican approaches',
  '搁浅扑腾': 'Stranded flop', '岸边蹦跳、侧翻与尾巴扭动': 'Hop, roll, and wriggle at the shore',
  '重新入水': 'Return to water', '岸边扑腾后回到水中': 'Flop back into the water from shore',
  '角色展示场': 'Character showcase', '角色历史资料库': 'Character history library',
  'Grassy · 正式装备角色': 'Grassy · Final equipment character',
  '键盘背负、呼吸与走路；切换跑跳、骑自行车、键盘战斗和推进飞行，三档精细度共用同一造型。': 'Inspect the carried keyboard, breathing, and walking. Switch to running, jumping, cycling, keyboard combat, and powered flight. Three detail levels share the same design.',
  '移动与跳跃': 'Movement and jumping', '比较走路、跑步和起跳落地；可以暂停、慢放与旋转观察。': 'Compare walking, running, and jumping; pause, slow down, and rotate the view.',
  'Grassy · 骑自行车': 'Grassy · Riding a bicycle', '坐稳车座、握住车把、双脚交替踩踏；车轮与链条同步转动，键盘保持背负。': 'Sit on the saddle, hold the handlebars, and pedal alternately. Wheels and chain rotate together while the keyboard stays on the back.',
  '普通攻击 · 砸键盘': 'Basic attack · Keyboard smash', '单手握住键盘短端，向左抡击、反手右挥；可切换起飞、悬停和前飞施法。': 'Grip one short end of the keyboard, swing left and backhand right; switch to attacks during takeoff, hovering, or forward flight.',
  '键盘左右连击、蓝白实体光弹、紫绿虫群与服务器超载；粒子与实体共同构成完整攻击效果。': 'Left and right keyboard strikes, blue white energy projectiles, a purple green bug swarm, and server overload combine solid forms with particles.',
  '施法姿态': 'Casting stance', '地面施法': 'Ground casting', '起飞施法': 'Takeoff casting', '悬停施法': 'Hover casting', '前飞施法': 'Forward-flight casting',
  'Grassy · 空中战斗': 'Grassy · Airborne combat', '起飞、悬停和前飞中施放四种键盘攻击；推进器持续工作，实体弹体与粒子同时可见。': 'Use four keyboard attacks during takeoff, hovering, and forward flight; thrusters keep running alongside solid projectiles and particles.',
  '起飞、悬停、前飞与降落；飞行时保持键盘背负。': 'Take off, hover, fly forward, and land while keeping the keyboard on the back.',
  'The Model Router 与 The Reset Master · 在横版游戏场景中展示动作、技能与受击效果，可切换左右朝向和地上地下。': 'The Model Router and The Reset Master demonstrate actions, skills, and impacts in the side-scrolling game world. Switch direction and surface or underground environments.',
  '七种鱼类': 'Seven fish species', '并排观察小鱼、金鱼、锦鲤、神仙鱼、鲶鱼、鲈鱼与虹鳟的轮廓和游动': 'Compare minnows, goldfish, koi, angelfish, catfish, bass, and rainbow trout side by side.',
  'Grassy · 历史版本': 'Grassy · Historical versions', '旧原画、比例稿、模型与工程归档': 'Archived concept art, proportions, models, and project files',
  '全部历史模型': 'All historical models', '归档的 18 个模型，使用原始模型与材质，可旋转和缩放检查。': 'Inspect 18 archived models with their original materials; rotate and zoom.',
  '建模方法对照': 'Modeling method comparison', '原画校准、多视图贴图和早期程序建模，保留各自的原始结果。': 'Compare concept alignment, multiview textures, and early procedural modeling in their original form.',
  'Rodin 精修过程': 'Rodin refinement', '对比原始 Rodin 与局部精修后的三档静态模型。': 'Compare original Rodin with three detail levels after local refinement.',
  '01 · 瓦片与形状': '01 · Tiles and shapes', '整格与半高度格优先展示；四种形状全部平铺，每张卡内八个自然样本。': 'Full and half height tiles appear first. All four shapes are laid out with eight natural samples per card.',
  '02 · 拼接与材质': '02 · Joins and materials', '连续地面、阶梯、跨材质邻接由游戏规则实时计算。': 'Continuous ground, steps, and mixed material joins are computed with game rules.',
  '03 · 植被分层': '03 · Vegetation layers', '同一地形与坐标：瓦片 → 地被 → 花草 → 完整植被。': 'Same terrain and coordinates: tiles → ground cover → flowers → full vegetation.',
  '04 · 生长环境': '04 · Growth habitats', '草地、裸土、沙地、近水、树下、地下，使用真实生长规则。': 'Grass, bare dirt, sand, shores, under trees, and underground use real growth rules.',
  '05 · 同种树的变化': '05 · Tree variants', '顶部选择树种，下方自动平铺 8 种种子变化。': 'Choose a tree above to compare eight seeded variants below.',
  '06 · 风动对照': '06 · Wind comparison', '选择树种，自动对照同种子在无风、微风、强风中的动画。': 'Choose a tree and compare calm, breeze, and strong wind animations for the same seed.',
  '07 · 场景组合': '07 · Scene compositions', '草甸、林地、岸边、沙漠、洞穴、渔屋，共用正式场景视图。': 'Meadow, woodland, shore, desert, cave, and fishing hut use the game scene views.',
  '08 · 地形组合': '08 · Terrain compositions', '相同范围内对照八种地形：平地、土丘、草沟、半格台阶、裂隙、洞口、树根坡地与浅水洼地。': 'Compare eight terrains in the same area: flat ground, mound, grass ditch, half tile steps, crevice, cave mouth, root slope, and shallow pool.',
  '场景资源展示场': 'Scene asset showcase', '地形瓦片': 'Terrain tiles', '完整瓦片注册表；树枝与屋顶通过所属模型展示': 'Complete tile catalog; branches and roofs use their game models',
  '树木': 'Trees', '全部树种，使用游戏生成规则、树冠和枝干': 'All tree species, using game generation rules, canopies, and trunks',
  '灌木': 'Shrubs', '全部灌丛与植株轮廓': 'All shrub and plant silhouettes',
  '花草': 'Flowers and grass', '自然组合与全部花草物种': 'Natural combinations and all flower species',
  '地被': 'Ground cover', '苔藓、嫩芽、落叶与垂挂地被': 'Moss, sprouts, leaf litter, and hanging ground cover',
  '岩石': 'Rocks', '碎石、巨石、地标岩与岩脚装饰': 'Pebbles, boulders, landmark rocks, and rock base decorations',
  '沙漠装饰': 'Desert decoration', '仙人掌、荒漠植物、骨骸与沙纹': 'Cacti, desert plants, bones, and sand patterns',
  '渔屋': 'Fishing hut', '完整屋顶、墙体、室内与栈桥': 'Complete roof, walls, interior, and pier',
  '水池': 'Water', '真实水体、波纹与全部配色': 'Real water, ripples, and every palette',
  '水生植物': 'Aquatic plants', '湖底、水面与悬浮植物的全部变体': 'All underwater, surface, and floating plant variants',
  '洞穴装饰': 'Cave decorations', '全部地面与顶壁装饰，保留游戏的悬挂方向': 'All floor and ceiling decorations with their game hanging directions',
  '游戏变体': 'Game variants', '空气（留空）': 'Air (empty)', '泥土': 'Dirt', '石头': 'Stone', '木平台': 'Wood platform',
  '草地': 'Grass', '沙地': 'Sand', '砂岩': 'Sandstone', '木料': 'Timber', '树枝平台（树模型）': 'Branch platform (tree model)', '屋顶（渔屋模型）': 'Roof (hut model)',
  '自然花草': 'Natural flowers', '右侧栈桥': 'Right pier', '左侧栈桥': 'Left pier', '清澈': 'Clear', '翡翠': 'Emerald', '深蓝': 'Deep blue',
  '平缓草地': 'Gentle meadow', '连续地面与成片植被，观察疏密和跨格衔接。': 'Continuous ground and broad vegetation show density and transitions across tiles.',
  '低矮土丘': 'Low mound', '两侧缓坡接入宽丘顶，草皮沿连续轮廓生长。': 'Gentle slopes lead to a wide crest, with grass following the continuous contour.',
  '下凹草沟': 'Grass gully', '坡肩、坡脚和沟底形成同一段凹地形。': 'Slope shoulders, feet, and bottom form one concave terrain section.',
  '半格台阶': 'Half tile steps', '整格和半格交替，以半格高差逐级上下。': 'Full and half tiles alternate in half tile height steps.',
  '裂口崖台': 'Split cliff', '完整崖台之间留出裂口，沟底保留实际落脚面。': 'A gap splits the cliff platforms while the bottom remains walkable.',
  '洞口土台': 'Cave entrance', '厚土顶由侧壁承托，可沿下坡进洞并原路返回。': 'Side walls support the thick roof; descend into the cave and return the same way.',
  '树根坡地': 'Root slope', '正式阔冠树的根盘贴合高低坡面，树冠平台可站立。': 'Roots follow the slopes of the game tree, whose canopy platform is walkable.',
  '浅水洼地': 'Shallow pool', '封闭浅盆、真实液体和岸边植物共同构成湿地。': 'A shallow basin, real water, and shore plants form a wetland.',
  '小鱼': 'Minnow', '灵巧的尖头小鱼，保留橙、蓝、银三种配色。': 'Agile pointed fish with orange, blue, and silver colorways.',
  '金鱼': 'Goldfish', '橙金色圆鼓鱼身，舒展的双叶扇尾。': 'Rounded orange gold body and broad double fan tail.',
  '锦鲤': 'Koi', '修长的乳白鱼身，红色斑块和宽阔尾鳍。': 'Long cream body with red patches and a wide tail.',
  '神仙鱼': 'Angelfish', '银黄菱形鱼身，深色竖纹、高背鳍与细长腹鳍。': 'Diamond shaped silver yellow body with dark bands and long fins.',
  '鲶鱼': 'Catfish', '深灰扁头和浅色腹部，嘴边长着舒展的触须。': 'Dark flat head, pale belly, and long whiskers.',
  '鲈鱼': 'Perch', '厚实的绿金鱼身，深色竖纹和锯齿状背鳍。': 'Sturdy green gold body with dark bands and a serrated dorsal fin.',
  '虹鳟': 'Rainbow trout', '流线银绿鱼身，粉色侧带与深色小斑点。': 'Streamlined silver green body with a pink stripe and dark spots.',
  '陪伴': 'Companion', '明亮光心轻轻呼吸，细碎光点在周围游动。': 'Bright core breathes softly while tiny particles orbit it.',
  '引路': 'Guide', '光团向前漂移，粒子在身后流动、渐隐，指示前进方向。': 'The light drifts forward, leaving fading particles to show the way.',
  '等候': 'Wait', '粒子收拢，亮度放缓，停留在原处等候。': 'Particles gather and dim as the light waits in place.',
  '提醒': 'Alert', '粒子向中心聚亮，暖白色光脉冲提示前方值得留意。': 'Particles brighten toward the center and pulse to signal something ahead.',
  '欢跃': 'Celebrate', '光团跃动，细碎粒子向外舒展、消散。': 'The light bounces and particles spread outward and fade.',
  '光子攻击': 'Photon attack', '聚光蓄势后向四面八方放射光束，冲击环与星屑逐渐散去。': 'Charge and emit beams in all directions, then let the shock ring and sparks fade.',
  '行走': 'Walk', '自然呼吸并眨眼，胸口、头部与双臂轻轻起伏。': 'Breathe and blink naturally, with gentle chest, head, and arm movement.',
  '交替迈步，观察短腿步态与双臂摆动。': 'Alternate steps to show short leg gait and arm swing.',
  '招呼': 'Greet', '抬起爪子打招呼，再恢复站姿。': 'Raise a paw to greet, then return to standing.',
  '特色技能': 'Signature skills',
  '前倾加速、蹬地腾空，短腿快速交替，双臂反向摆动。': 'Lean into a fast run with airborne strides and opposite arm swings.',
  '屈膝蓄力、跃起收腿，落地缓冲后恢复站姿。': 'Crouch, spring upward, tuck the legs, and absorb the landing before standing.',
  '模型路由攻击': 'Model Routing Attack', '头顶 GPT-6 Astra 核心斜射蓝金光线；命中后，目标身上显现 GPT-5.6 Luna 或 GPT-4o mini。光线沿固定方向飞行，可以跳跃躲避。': 'The overhead GPT-6 Astra core fires blue-gold beams downward. GPT-5.6 Luna or GPT-4o mini appears on the target only on impact. Jump to dodge the fixed paths.',
  '目标躲避': 'Target dodge',
  '算力激涌': 'Compute Surge', '算力凝成 Token 导弹，沿高低弧线连续发射，命中后爆散成数据碎块。': 'Form Token missiles, launch them in staggered arcs, and shatter them into data fragments on impact.',
  'AGI 降临': 'AGI Advent', '召来 AGI 天穹，巨型光柱与蓝金冲击波连续击退两侧训练靶。': 'Summon an AGI canopy, a towering beam, and blue-gold shockwaves that repeatedly knock back both training targets.',
  '薯条攻击': 'Fries Attack', '抛出金黄薯条与俏皮文字，金橙弹道连续命中训练靶，文字为攻击助威。': 'Toss golden fries and playful words as golden volleys hit the training targets, cheered on by comic text.',
  '额度返场': 'Quota Encore', '按下重置按钮补满额度，绿色能量命中前方训练靶，爆出金色碎片。': 'Press the reset button to refill the quota, then hit the targets ahead with green energy and golden fragments.',
  '重置降临': 'Reset Descends', '巨型重置按钮降临，绿金冲击连续覆盖两侧训练靶，弹起并爆散粒子。': 'A giant reset button descends; green-gold waves repeatedly strike both training targets, launching them amid bursts of particles.',
  '观察角度': 'View angle', '自由视角 / 各卡不同': 'Free view / Varies by card', '恢复正面': 'Reset to front',
  '点击换角度 · 拖动旋转': 'Click to change angle · Drag to rotate',
  '模型视角': 'Model view', '自由视角': 'Free view', '视角复位': 'Reset view',
  '拖动旋转 · 双击复位': 'Drag to rotate · Double click to reset',
  '橡树': 'Oak', '阔叶树': 'Broadleaf tree', '松树': 'Pine', '矮树': 'Small tree', '棕榈': 'Palm',
  '樱花树': 'Cherry blossom', '柳树': 'Willow', '白桦': 'Birch', '枯树': 'Dead tree',
  '草皮': 'Turf', '草丛': 'Grass tuft', '高草': 'Tall grass', '芦苇': 'Reed', '三叶草': 'Clover',
  '雏菊': 'Daisy', '罂粟花': 'Poppy', '风铃草': 'Bluebell', '蒲公英': 'Dandelion', '向日葵': 'Sunflower',
  '薰衣草': 'Lavender', '蕨叶': 'Fern', '小灌丛': 'Small shrub', '蘑菇': 'Mushroom', '小石子': 'Pebble',
  '垂藤': 'Hanging vine', '蝴蝶': 'Butterfly', '绿篱': 'Hedge', '杜鹃': 'Azalea', '浆果': 'Berry bush',
  '蕨丛': 'Fern clump', '幼树': 'Sapling', '香蒲': 'Cattail', '玫瑰': 'Rose', '竹丛': 'Bamboo',
  '滨草': 'Beach grass', '沙棘': 'Sea buckthorn',
  '地表苔藓': 'Ground moss', '贴地三叶草': 'Creeping clover', '卷蕨': 'Fiddlehead fern',
  '莲座叶': 'Leaf rosette', '嫩芽': 'Sprout', '地衣': 'Lichen', '幼苗': 'Seedling', '落叶': 'Leaf litter', '垂挂地被': 'Hanging ground cover',
  '碎石': 'Pebbles', '卵石': 'Cobbles', '石砾': 'Rubble', '沙地碎石': 'Sand pebbles',
  '花岗岩 A': 'Granite A', '花岗岩 B': 'Granite B', '层理岩 A': 'Layered rock A', '层理岩 B': 'Layered rock B',
  '板岩': 'Slate', '大卵石': 'Large cobble', '湖岸石 A': 'Shore stone A', '湖岸石 B': 'Shore stone B',
  '沙地岩块': 'Sandstone block', '巨石': 'Boulder', '露岩': 'Outcrop', '沙地巨石': 'Desert boulder',
  '沙地露岩': 'Desert outcrop', '岩壁': 'Rock wall', '砂岩柱': 'Hoodoo', '岩石拱门': 'Rock arch',
  '草地岩脚': 'Grass rock base', '沙地岩脚': 'Sand rock base', '岩缝草': 'Crevice grass',
  '柱状仙人掌': 'Saguaro cactus', '开花柱状仙人掌': 'Blooming saguaro', '多枝大仙人掌': 'Branched saguaro',
  '球状仙人掌': 'Barrel cactus', '开花球状仙人掌': 'Blooming barrel cactus', '掌片仙人掌': 'Prickly pear',
  '蜡烛木': 'Ocotillo', '丝兰': 'Yucca', '龙舌兰': 'Agave', '芦荟': 'Aloe', '黄色野花': 'Yellow wildflower',
  '紫色野花': 'Purple wildflower', '干枯灌木': 'Dry shrub', '干草': 'Dry grass', '枯枝': 'Dead branch',
  '枯枝堆': 'Dead branch pile', '头骨': 'Skull', '散骨': 'Scattered bones', '沙丘风纹': 'Dune ripples', '碎石贝壳': 'Pebbles and shells',
  '金鱼藻': 'Hornwort', '水韭': 'Quillwort', '苦草': 'Eelgrass', '藻毯': 'Algae mat', '附石藻': 'Rock algae',
  '浮萍': 'Duckweed', '睡莲叶': 'Lily pad', '睡莲花': 'Water lily', '水鳖': 'Frogbit', '漂叶': 'Floating leaf',
  '藻丝': 'Algae thread', '悬浮絮片': 'Floating flake', '水中微粒': 'Water mote',
  '骑行模型': 'Riding model', '默认视角': 'Default view',
  '推进飞行 · 装备定稿': 'Powered flight · Final equipment', '键盘武器 · Codex 攻击': 'Keyboard weapon · Codex attack',
  '非攻击姿态 · 键盘背负': 'Idle pose · Keyboard on back', '正式装备模型': 'Final equipped model',
  'Grassy 骑自行车': 'Grassy on bicycle', 'Grassy · 人类形态': 'Grassy · Human form',
  'Grassy · 鹈鹕形态': 'Grassy · Pelican form', '人形定稿': 'Final human design', '右侧母版': 'Right master view',
  '2D 原画 · 四分之三': '2D concept · Three quarter', '2D 原画 · 正侧面': '2D concept · Profile',
  '2D 原画 · 对齐版': '2D concept · Aligned', '3D 参考 · 白色修订版': '3D reference · White revision',
  '3D 参考 · 早期侧面': '3D reference · Early profile', '3D 参考 · 四分之三': '3D reference · Three quarter',
  '3D 参考 · 对齐版': '3D reference · Aligned', '细修版': 'Refined version', '原版': 'Original version',
  '俯视': 'Top', '翅膀特写': 'Wing closeup', '2D 起点': '2D starting point', '体积过渡': 'Volume transition',
  '3D 终点': '3D final result', '正面试稿': 'Front study', '侧面透明底': 'Transparent side view',
  '侧面': 'Side', '湖边骑行': 'Riding by the lake', '自行车插画': 'Bicycle illustration',
  '骑行预览': 'Riding preview', '骑行动画': 'Riding animation', '骑行插画': 'Riding illustration',
  '骑车原稿': 'Original riding art', '海岸骑行原始参考': 'Original coastal riding reference',
  '旧呼吸与走路': 'Old breathing and walk', '历史资源说明与工程索引': 'Historical assets and project index',
  '完整迁移清单': 'Full migration manifest', '门框对照': 'Doorway comparison',
  '3.1 格定稿': 'Final 3.1 tile design', '初稿': 'First draft', '增高试稿': 'Taller study',
  '角色卡探索': 'Character card study', '第一版': 'Version one', '第二版': 'Version two',
  '第三版': 'Version three', '第四版': 'Version four', '头身比例': 'Body proportions',
  '并排比较': 'Side by side', '游戏视距': 'Game distance', '场景比例': 'Scene scale',
  '近景': 'Close view', '侧面原画入场景': 'Profile concept in scene',
  '第一轮': 'Round one', '第四轮第 1 批': 'Round four, batch one', '第四轮第 2 批': 'Round four, batch two',
  '第四轮第 3 批': 'Round four, batch three', '第四轮第 4 批': 'Round four, batch four',
  '原画校准版 · 形体修正': 'Concept aligned · Shape correction',
  '多视图贴图版 · 原画质感': 'Multiview textures · Concept art style',
  '精细版': 'Detailed', '游戏标准版': 'Game standard', '游戏轻量版': 'Game light',
  '呼吸': 'Breathe', '键盘磁吸背负，胸腹轻微起伏，肩膀放松，双脚保持接地。': 'Keyboard magnetically secured on the back; chest and belly breathe gently, shoulders relax, and feet stay grounded.',
  '键盘背负，原地迈步，屈膝抬脚与双臂反向摆动。': 'Walk in place with the keyboard on the back, bending knees and swinging arms opposite the legs.',
  '身体前倾、蹬地腾空，双臂配合快速跑动，键盘固定在背架上。': 'Lean forward, push off the ground, and run quickly with the keyboard secured on the back.',
  '骑自行车': 'Ride bicycle', '坐在车座上，双手握车把、双脚交替踩踏，车轮和链条同步转动，键盘保持背负。': 'Sit on the saddle, hold the handlebars, and pedal alternately; wheels and chain turn together, with keyboard on the back.',
  '跳跃': 'Jump', '屈膝蓄力、起跳收腿、下落与落地缓冲，键盘保持背负。': 'Crouch, jump, tuck legs, fall, and absorb the landing while carrying the keyboard.',
  '右手握住键盘短端，抡起远端左右横击，左手张开保持平衡，连击后收回背上。': 'Grip one short end with the right hand and swing the far end left and right, extending the left hand for balance, then stow the keyboard on the back.',
  'Codex 攻击': 'Codex attack', '键盘连发蓝白实体光弹，白热弹芯、长尾流与代码粒子贯穿远处。': 'Fire blue white solid energy bolts with brilliant cores, long trails, and code particles across the distance.',
  'Bug 攻击': 'Bug attack', '紫绿实体虫群沿弹道前冲，发光腹核、翅足与故障粒子形成持续攻势。': 'Purple green solid bugs surge forward with glowing cores, wings, legs, and glitch particles.',
  '服务器超载': 'Server overload', '服务器阵列过热转红，白热能量柱爆发，多层冲击波裹挟实体碎片向外扩散。': 'The server array overheats to red, a brilliant energy column erupts, and layered shockwaves carry solid debris outward.',
  '起飞': 'Takeoff', '推进器启动，双腿离地并进入悬停姿势，键盘背负。': 'Thrusters ignite, lifting both legs into a hover while the keyboard remains on the back.',
  '悬停': 'Hover', '护腕和背部推进器稳定输出，屈膝悬停并轻微调整平衡。': 'Wrist and back thrusters hold a steady hover while knees and posture adjust balance.',
  '向前飞行': 'Fly forward', '身体前倾、双腿后收，推进尾流增强，键盘保持背负。': 'Lean forward, draw legs back, and boost the thruster trail with keyboard on the back.',
  '降落': 'Land', '降低推进输出、双脚接地并屈膝缓冲，推进器熄灭。': 'Reduce thrust, touch down with bent knees, and let the thrusters fade.',
  '白鼬山姆 · 棕色短发、蓝灰眼睛、灰毛衣与路由胸章。': 'Sam the ermine · Short brown hair, blue gray eyes, gray sweater, and routing badge.',
  '鼹鼠提博 · 侧分头发、开朗笑容、黑色帽衫与重置胸章。': 'Tibo the mole · Side parted hair, cheerful smile, black hoodie, and reset badge.',
  '☀ 地上': '☀ Above ground', '◐ 地下': '◐ Underground', '◐ 地下 · 检视补光': '◐ Underground · Inspection light',
  '正在加载模型…': 'Loading model…', '离屏自动暂停': 'Pause when offscreen',
};

const patterns: ReadonlyArray<readonly [RegExp, string]> = [
  [/^(\d+) 张预览$/, '$1 previews'], [/^(\d+) 个动作$/, '$1 actions'], [/^(\d+) 个变体$/, '$1 variants'],
  [/^最多同时预览 (\d+) 张卡，请先关闭一张$/, 'Up to $1 cards at once; close one first'],
  [/^已达 (\d+) 张上限，请先关闭一张预览$/, 'Limit of $1 cards reached; close one preview'],
  [/^图片资源 · (\d+)$/, 'Images · $1'], [/^种子 (\d+)$/, 'Seed $1'],
  [/^资源加载失败：(.*)$/, 'Asset failed to load: $1'],
  [/^查看(.+)$/, 'View $1'],
  [/^(.*)预览图片$/, '$1 preview image'],
  [/^第 (\d+) \/ (\d+) 批$/, 'Batch $1 / $2'],
  [/^搜索(资源|历史角色|角色)…$/, 'Search $1…'],
  [/^(资源|历史角色|角色)目录$/, '$1 catalog'],
  [/^没有匹配的(资源|历史角色|角色)$/, 'No matching $1'],
  [/^选择一个(资源|历史角色|角色)，开始查看$/, 'Choose a $1 to begin'],
  [/^选择(.+)$/, 'Select $1'],
  [/^勾选左侧(资源|历史角色|角色)卡；使用「添加对照」比较不同(变体|动作)或环境。$/, 'Select a $1 card on the left; use Add comparison to compare $2 or environments.'],
  [/^最多 (\d+) 张预览卡 · (变体|动作)在右侧切换$/, 'Up to $1 preview cards · Change $2 on the right'],
  [/^(\d+) 个历史模型$/, '$1 historical models'],
  [/^(\d+) 种 · 第 (\d+) \/ (\d+) 批 · (\d+)–(\d+)$/, '$1 variants · Batch $2 / $3 · $4–$5'],
  [/^查看(.+)全部变体，每批最多 (\d+) 张（替换当前预览）$/, 'View all $1 variants, up to $2 per batch (replaces current previews)'],
  [/^场景组合 · (.*)$/, 'Scene composition · $1'],
  [/^青线：可站立$/, 'Cyan: walkable'],
  [/^八个自然样本 (\d+)–(\d+)$/, 'Eight natural samples $1–$2'],
  [/^样本 (\d+)$/, 'Sample $1'],
  [/^变化 (\d+)$/, 'Variant $1'],
  [/^独立预览 · (\d+) 个画面可见 · 离屏自动暂停$/, 'Independent previews · $1 views visible · Paused when offscreen'],
  [/^(.+) · 正在加载模型…$/, '$1 · Loading model…'],
  [/^(\d+(?:\.\d+)?) 头身$/, '$1 heads tall'],
  [/^石笋 ([A-D])$/, 'Stalagmite $1'], [/^钟乳石 ([A-D])$/, 'Stalactite $1'],
  [/^发光蘑菇 ([A-C])$/, 'Glowing mushroom $1'], [/^青晶 ([A-B])$/, 'Cyan crystal $1'],
  [/^悬垂青晶 ([A-B])$/, 'Hanging cyan crystal $1'], [/^紫晶 ([A-B])$/, 'Purple crystal $1'],
  [/^悬垂紫晶 ([A-B])$/, 'Hanging purple crystal $1'], [/^洞穴苔藓 ([A-B])$/, 'Cave moss $1'],
  [/^垂挂苔藓 ([A-B])$/, 'Hanging moss $1'], [/^蛛网 ([A-B])$/, 'Cobweb $1'],
  [/^水平 (-?\d+)° \/ 俯仰 (-?\d+)°$/, 'Yaw $1° / pitch $2°'],
  [/^(.+)，(.+)。点击或按左右方向键切换角度，拖动自由旋转。$/, '$1, $2. Click or use left and right arrows to change angle; drag to rotate freely.'],
  [/^(.+) · 点击切换角度，拖动旋转，左右方向键切换角度$/, '$1 · Click to change angle, drag to rotate, or use left and right arrows'],
  [/^(.+)，(.+)。拖动或按方向键旋转，双击或按 Home 复位。$/, '$1, $2. Drag or use arrow keys to rotate; double click or press Home to reset.'],
  [/^(.+) · 左右拖动旋转，上下拖动俯仰，双击复位$/, '$1 · Drag horizontally to rotate or vertically to tilt; double click to reset'],
];

export function translateShowcaseText(source: string): string | undefined {
  const exact = SHOWCASE_ENGLISH[source];
  if (exact) return exact;
  const categoryCount = source.match(/^(装备概念|战斗效果概念|空中技能概念|历史模型多视图|早期角色卡|场景比例对照|头身比例稿|早期四方向|3\.1 比例试稿|四方向修订稿|母版试稿|角色卡|四方向参考|2D 原画|3D 参考|模型多视图|演变对照|历史版本|骑行素材|骑行模型) (\d+)$/);
  if (categoryCount) return `${SHOWCASE_ENGLISH[categoryCount[1]!] ?? categoryCount[1]} ${categoryCount[2]}`;
  const actionDescription = source.match(/^(精细版|游戏标准版|游戏轻量版)：(.+)$/);
  if (actionDescription) return `${SHOWCASE_ENGLISH[actionDescription[1]!]}: ${SHOWCASE_ENGLISH[actionDescription[2]!] ?? actionDescription[2]}`;
  const actorAction = source.match(/^(.+) · (呼吸|走路|跑步|骑自行车|跳跃|普通攻击 · 砸键盘|Codex 攻击|Bug 攻击|服务器超载|起飞|悬停|向前飞行|降落)$/);
  if (actorAction) return `${SHOWCASE_ENGLISH[actorAction[1]!] ?? actorAction[1]} · ${SHOWCASE_ENGLISH[actorAction[2]!]}`;
  const loadingAction = source.match(/^(.+) · 正在加载模型…$/);
  if (loadingAction) return `${SHOWCASE_ENGLISH[loadingAction[1]!] ?? loadingAction[1]} · Loading model…`;
  for (const [pattern, replacement] of patterns) if (pattern.test(source)) {
    const translated = source.replace(pattern, replacement);
    return translated.replace(/历史角色|资源|角色|变体|动作|装备概念|战斗效果概念|空中技能概念|历史模型多视图|早期角色卡|场景比例对照|头身比例稿|早期四方向|3\.1 比例试稿|四方向修订稿|母版试稿|角色卡|四方向参考|2D 原画|3D 参考|模型多视图|演变对照|历史版本|骑行素材/g, (part) => SHOWCASE_ENGLISH[part] ?? ({ 资源: 'asset', 历史角色: 'historical character', 角色: 'character', 变体: 'variant', 动作: 'action' })[part]!);
  }
  if (source.includes(' · ')) {
    const pieces = source.split(' · ');
    const translated = pieces.map((piece) => SHOWCASE_ENGLISH[piece] ?? piece.replace(/^种子 (\d+)$/, 'Seed $1'));
    if (translated.some((piece, index) => piece !== pieces[index])) return translated.join(' · ');
  }
  return undefined;
}
