"""Publish the natural-resource Markdown and its static concept-page snapshots."""
from pathlib import Path
import html
import json
import re
import shutil
from PIL import Image

ROOT=Path(__file__).resolve().parents[3]
KINDS=('grass','flower','shrub','bonsai','tree','vine','drooping','rock','ore')

def inline(text):
    text=html.escape(text)
    text=re.sub(r'`([^`]+)`',r'<code>\1</code>',text)
    text=re.sub(r'\*\*([^*]+)\*\*',r'<strong>\1</strong>',text)
    def link(match):
        label,url=match.groups()
        if url.endswith('.md') and '/' not in url:url='./concepts/'+url
        return f'<a href="{url}">{label}</a>'
    return re.sub(r'\[([^\]]+)\]\(([^)]+)\)',link,text)

def markup(path,kind=None):
    result=[]
    for block in path.read_text().strip().split('\n\n'):
        if block.startswith('# '):
            if kind:result.append('<h2>'+inline(block[2:])+'</h2>')
        elif block.startswith('## '):result.append('<h3>'+inline(block[3:])+'</h3>')
        elif block.startswith('!['):
            match=re.fullmatch(r'!\[([^\]]*)\]\(([^)]+)\)',block)
            alt,url=match.groups();url='.'+url
            with Image.open(ROOT/'public'/url.removeprefix('./')) as picture:width,height=picture.size
            result.append(f'<figure class="concepts-figure"><a href="{url}" target="_blank" rel="noopener"><img src="{url}" width="{width}" height="{height}" loading="lazy" alt="{html.escape(alt)}" /></a><figcaption>点击查看完整透视、尺寸与空间关系图。</figcaption></figure>')
        elif block.startswith('|'):
            rows=block.splitlines();result.append('<div class="concepts-table-scroll"><table>')
            for i,row in enumerate(rows):
                if i==1:continue
                tag='th' if i==0 else 'td'
                result.append('<tr>'+''.join(f'<{tag}>{inline(cell.strip())}</{tag}>' for cell in row.strip('|').split('|'))+'</tr>')
            result.append('</table></div>')
        elif block.startswith('- '):result.append('<ul>'+''.join('<li>'+inline(line[2:])+'</li>' for line in block.splitlines())+'</ul>')
        else:result.append('<p>'+inline(block)+'</p>')
    return '\n'.join(result)

main=ROOT/'docs/natural-resource-definitions.md'
sections=[]
for kind in KINDS:
    path=ROOT/f'docs/natural-{kind}-definitions.md'
    shutil.copyfile(path,ROOT/f'public/concepts/{path.name}')
    sections.append(f'<section id="natural-{kind}" class="help-block">'+markup(path,kind)+f'<p><a class="help-text-link" href="./concepts/{path.name}" target="_blank" rel="noopener">打开本类独立定义文档 ↗</a></p></section>')
shutil.copyfile(main,ROOT/f'public/concepts/{main.name}')
output='// Generated by assets/concepts/scene-depth-guide/build_natural_resource_documents.py from docs/natural-*.md.\n'
output+='export const NATURAL_RESOURCE_DOCUMENT = '+json.dumps(markup(main),ensure_ascii=False)+';\n'
spatial=ROOT/'docs/natural-spatial-definitions.md'
shutil.copyfile(spatial,ROOT/'public/concepts/natural-spatial-definitions.md')
output+='export const NATURAL_SPATIAL_DOCUMENT = '+json.dumps(markup(spatial,'spatial'),ensure_ascii=False)+';\n'
output+='export const NATURAL_RESOURCE_STATES = '+json.dumps('\n'.join(sections),ensure_ascii=False)+';\n'
(ROOT/'src/ui/concept-natural-resources.ts').write_text(output)
print(f'Published {len(KINDS)} independent definitions, overall reference and page snapshots.')
